# dataset
data_root: ../datasets/
dataset: web-car
n_classes: 196
rescale_size: 448
crop_size: 448

# network & optimization
arch: resnet18
opt: sgd
batch_size: 64
epochs: 100
lr: 0.01
lr_decay: cosine:5,0.0,100
warmup_epochs: 5
warmup_lr: 0.01
warmup_lr_plan: constant
weight_decay: 1.0e-5
use_fp16: True

# hyper-params
eps: 0.3
alpha: 0.1

# logging
log_root: ../results/
log_proj: ''
log_name: IterJoSRC

